models/Platos.php
<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;
use app\models\Productos;
/**
 * This is the model class for table "platos".
 *
 * @property int $id
 * @property string $nombre
 * @property int|null $categoria
 * @property float|null $precio_publico
 * @property float|null $coste
 *
 * @property Categorias $categoria0
 * @property Comandas[] $comandas
 * @property GuarnicionesEnPlatos[] $guarnicionesEnPlatos
 * @property ProductosEnPlatos[] $productosEnPlatos
 */
class Platos extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'platos';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['nombre'], 'required','message'=>'El nombre no puede estar vacio'],
            [['nombre'], 'string', 'max' => 200],
            [['nombre'], 'match','pattern'=>'/^[a-z,.\s-]+$/i','message'=>'Nombre no válido, no uses números ni carácteres extraños'],
            [['precio_publico', 'coste'], 'number','min' => 0.01],            
            [['categoria'], 'exist', 'skipOnError' => true, 'targetClass' => Categorias::class, 'targetAttribute' => ['categoria' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'categoria' => 'Categoría',
            'precio_publico' => 'Precio de venta',
            'coste' => 'Coste de fabricación',
        ];
    }
    
    /**
     * Gets query for [[Categoria0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategoria0()
    {
        return $this->hasOne(Categorias::class, ['id' => 'categoria']);
    }

    /**
     * Gets query for [[Comandas]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getComandas()
    {
        return $this->hasMany(Comandas::class, ['id_plato' => 'id']);
    }

    /**
     * Gets query for [[GuarnicionesEnPlatos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getGuarnicionesEnPlatos()
    {
        return $this->hasMany(GuarnicionesEnPlatos::class, ['id_plato' => 'id']);
    }

    public function getGuarniciones()
    {
        return $this->hasMany(Guarniciones::class, ['id' => 'id_guarnicion'])
                ->viaTable('guarniciones_en_platos', ['id_plato'=>'id'])
                ->orderBy('id ASC');
    }

    public function getPrecioGuarniciones($idguarnicion)
    {
        $models = Yii::$app->db->createCommand('select sum(precio_compra) precio from productos 
        left join productos_en_guarniciones
        on productos.id = productos_en_guarniciones.id_producto
        where productos_en_guarniciones.id_guarnicion = '.$idguarnicion)->queryAll();

        return $models;
    }
    /**
     * Gets query for [[ProductosEnPlatos]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getProductosEnPlatos()
    {
        return $this->hasMany(ProductosEnPlatos::class, ['id_plato' => 'id'])
                ->orderBy('id_producto ASC');
    }
    
    public function getProductos()
    {
        return $this->hasMany(Productos::class, ['id' => 'id_producto'])
                ->viaTable('productos_en_platos', ['id_plato'=>'id'])
                ->orderBy('id ASC');
    }
    

    public function getdropdownCategoria(){
        $models = Categorias::find()->asArray()->all();
        
        return ArrayHelper::map($models, 'id', 'nombre');
    }

}

controllers/PlatosController.php
<?php

namespace app\controllers;

use app\models\Categorias;
use app\models\Platos;
use app\models\Productos;
use \app\models\ProductosEnPlatos;
use yii\data\ActiveDataProvider;
use yii\data\SqlDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PlatosController implements the CRUD actions for Platos model.
 */
class PlatosController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Platos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        
        $dataProvider = new ActiveDataProvider([
            'query' => Platos::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Platos model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
      
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Platos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Platos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['receta']);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->renderAjax('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Platos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['receta']);
        }

        return $this->renderAjax('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Platos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['receta']);
    }

    /**
     * Finds the Platos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Platos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Platos::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('La página solicitada no existe');
    }
    
    public function actionReceta() {
        
        $dataProvider = new ActiveDataProvider([
            'query' => Platos::find(),
        ]);
        
        return $this->render('vistaPlatos',[
           'dataProvider' => $dataProvider,
        ]);
    }
    
    public function actionMostrarrecetas(){
        $platos = new ActiveDataProvider([
            'query' => Platos::find(),
        ]);
        
        $ingredientes = new ActiveDataProvider([
           'query'=> ProductosEnPlatos::find()->joinWith('productos'),
        ]);
        
        return $this->render('vistaPlatos',[
           'datos' => [
               'platos'=>$platos,
               'ingredientes'=>$ingredientes,
               ],
        ]);
    }
}

views/platos/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

$modelProductos = new app\models\ProductosEnPlatos;

/* @var $this yii\web\View */
/* @var $model app\models\Platos */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="platos-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'nombre')->textInput(['maxlength' => true])->label('Nombre',['class'=>'texto-formularios']) ?>

    <?= $form->field($model, 'categoria')->dropDownList($model->getdropdownCategoria())->label('Categoría',['class'=>'texto-formularios']) ?>

    <?= $form->field($model, 'precio_publico')->textInput(['maxlength' => true])->label('Precio de venta',['class'=>'texto-formularios']) ?>
    
    
    
    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'shadow lift btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/platos/_vistaPlatos.php
<?php
 use yii\helpers\ArrayHelper;
 use yii\helpers\Html;
 use yii\helpers\Url;
 
 use kartik\icons\Icon;

Icon::map($this, Icon::FA);

yii\bootstrap4\Modal::begin([
    'title'=>'',
    'titleOptions'=>['class'=>"title-modal-extendido"],
    'headerOptions'=>['class'=>"header-modal-extendido"],
    'closeButton' =>['class'=>"btn btn-link boton-cerrar-modal"],
    'bodyOptions' =>['class'=>"modal-body-extendido"],
    'centerVertical'=>true,
   'id'     =>"modal$model->id",
   'size'   =>'modal-md',
   'clientOptions' => ['backdrop' => 'static', 'keyboard' => FALSE]
   ]);
echo "<div id='modalContent$model->id'> </div>";
yii\bootstrap4\Modal::end();

$idProd = ArrayHelper::getColumn($model->productosEnPlatos, 'id');
$nomProd = ArrayHelper::getColumn($model->productos,'nombre');

$idGuarnicion = ArrayHelper::getColumn($model->guarnicionesEnPlatos, 'id');
$precioGuarnicion = ArrayHelper::getColumn($model->guarniciones, 'coste');
$nomGuarnicion = ArrayHelper::getColumn($model->guarniciones, 'nombre');

$totalIngedientes = 0;
$totalGuarniciones = 0;
?>


<div class="card shadow">
    <div class="card-header card-header-extendido">
        <div class="row pt-2">
            <div class="col-4">
                <p class="h5 mx-3 align-middle text-uppercase">Nombre:</p>
                <p class="align-middle mx-3"> <?= $model->nombre ?></p>
            </div>
            <div class="col-4 text-center">
                <p class=" h5 text-uppercase">Categoria:</p>
                <p class=""> <?= $model->categoria0->nombre ?></p>
            </div>        
            <div class="col-4 text-right">
                <p class="h5 text-uppercase">Precio:</p>
                <p class=""> <?= $model->precio_publico." €" ?></p>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-3 text-left">
                <h5 class="text-muted mx-3">Ingredientes:</h5>
                    <?php 
                        for ($i = 0; $i <= count($idProd)-1; $i++) {
                            echo '<p class="mx-3 m-0 arreglo">'.$nomProd[$i];
                        }
                    ?>
            </div>
            <div class="col-3">
                <h5 class="text-muted text-right">Gramos:</h5>
                <p class="m-0 text-right">
                    <?php 
                        if(ArrayHelper::getColumn($model->productosEnPlatos,'gramos_producto')!=null){
                            echo implode(' gr</p><p class="m-0 text-right arreglo">',ArrayHelper::getColumn($model->productosEnPlatos,'gramos_producto')).' gr';
                        }
                    ?>
                </p>
            </div>
            <div class="col-3">
                <h5 class="text-muted text-right">Pvp:</h5>
                <p class="m-0 text-right">
                    <?php 
                        $precio = ArrayHelper::getColumn($model->productos,'precio_compra');
                        $gproducto = ArrayHelper::getColumn($model->productosEnPlatos,'gramos_producto');
                        $calculo = 0;
                        
                        $coste[]=0;
                        $coste2[]=0;
                        if(count($gproducto)>0){
                                for($i=0;$i<count($gproducto);$i++){
                                    $calculo = ($precio[$i] * $gproducto[$i])/60;
                                    $coste[$i] = number_format($calculo,2);
                                    $coste2[$i] = number_format($calculo,2).' €';
                                    $totalIngedientes += floatval($coste[$i]);
                            }
                        }
                        
                    ?>
                    <?php
                        if( sizeof($coste2) >= 1) {
                            echo implode('</p><p class="m-0 text-right arreglo">',$coste2);
                        };
                     ?>
                </p>
            </div>
            <div class="col-3 text-right">
                <h5 class="text-muted mx-3">Opciones:</h5>
                    <?php 
                    if(sizeof($idProd)>0){
                        for ($i = 0; $i <= count($idProd)-1; $i++) {
                            echo '<p class="mx-3 m-0">'
                                .Html::button(Icon::show('pen', ['class' => 'text-muted fa-solid', 'framework' => Icon::FAS]),['value'=>Url::to(['productos-en-platos/update2','id'=>$idProd[$i]]),
                                'class' => 'buttonmodal btn btn-link p-0',
                                'id'=>'#modalButton'.$model->id, 
                                'data-id'=>$model->id,
                                'data-tittle'=>'Editar cantidad']).' '.
                                Html::a(Icon::show('trash', ['class' => 'text-muted fa-solid', 'framework' => Icon::FAS]), ['productos-en-platos/delete', 'id' => $idProd[$i]], [
                                    'class' => 'btn btn-link p-0',
                                    'data' => [
                                        'head'=>'Confirmación',
                                        'confirm' => '¿Estás seguro que quieres eliminar '.$nomProd[$i].'?',
                                        'method' => 'post',
                                    ],
                                ]);
                        }
                    }
                    ?>
            </div>
        </div>
        <div class="col-12">
            <?= 
                Html::button(Icon::show('plus', ['class' => 'text-muted fa-solid', 'framework' => Icon::FAS])."Ingrediente",
                ['value'=>Url::to(['productos-en-platos/createid','plato'=>$model->id]),
                'class' => 'buttonmodal btn btn-link',
                'id'=>'#modalButton'.$model->id, 
                'data-id'=>$model->id,
                'data-tittle'=>'Añadir ingrediente'])
            ?>
        </div>
        <hr>
        <div class="row">
            <div class="col-3 text-left">
                    <h5 class="text-muted mx-3">Guarniciones:</h5>
                        <?php 
                        if(sizeof($idGuarnicion)>0){
                            for ($i = 0; $i <= count($idGuarnicion)-1; $i++) {
                                echo '<p class="mx-3 m-0">'.$nomGuarnicion[$i];
                            }
                        }
                            
                        ?>
            </div>
            <div class="col-6">
                <h5 class="text-muted text-right">Pvp:</h5>
                <p class="m-0 text-right">
                    <?php 
                        if(sizeof($precioGuarnicion)>0){
                            echo implode(' €</p><p class="m-0 text-right arreglo">',$precioGuarnicion).' €';
                        }else{
                        
                        }
                        foreach ($precioGuarnicion as $key => $value) {
                            $totalGuarniciones += $value;
                        }
                    ?>
                </p>
            </div>
            <div class="col-3 text-right">
                <h5 class="text-muted mx-3">Opciones:</h5>
                    <?php 
                    if(sizeof($idGuarnicion)>0){
                        for ($i = 0; $i <= count($idGuarnicion)-1; $i++) {
                            echo '<p class="mx-3 m-0">'
                                .
                                Html::a(Icon::show('trash', ['class' => 'text-muted fa-solid', 'framework' => Icon::FAS]), ['guarniciones-en-platos/delete', 'id' => $idGuarnicion[$i]], [
                                    'class' => 'btn btn-link p-0',
                                    'data' => [
                                        'head'=>'Confirmación',
                                        'confirm' => '¿Estás seguro que quieres eliminar '.$nomGuarnicion[$i].'?',
                                        'method' => 'post',
                                    ],
                                ]);
                        }
                    }
                    ?>
            </div>
        </div>
        <div class="col-12">
            <?=
                Html::button(Icon::show('plus', ['class' => 'text-muted fa-solid', 'framework' => Icon::FAS])."Guarnición",
                ['value'=>Url::to(['guarniciones-en-platos/create2','id'=>$model->id]),
                'class' => 'buttonmodal btn btn-link',
                'id'=>'#modalButton'.$model->id, 
                'data-id'=>$model->id,
                'data-tittle'=>'Añadir guarnición']) 
            ?>
        </div>
        <hr>
        <div class="row">
            <div class="col-6">
                <p class="mx-3">Coste total:</p>
            </div>
            <div class="col-6 text-right">
                <?php 
                        echo $totalIngedientes+$totalGuarniciones.' €';
                ?>
            </div>
        </div>
        <div class="">
            <p class="text-right m-0">
            <?= 
                Html::button("Editar",['value'=>Url::to(['platos/update','id'=>$model->id]),
                'class' => 'buttonmodal shadow lift btn btn-primary',
                'id'=>'#modalButton'.$model->id, 
                'data-id'=>$model->id,
                'data-tittle'=>'Editar plato']) 
            ?>
            <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'head'=>'Confirmación',
                    'confirm' => '¿Estás seguro que quieres eliminar '.$this->title.'?',
                    'method' => 'post',
                ],
            ]) ?>
            </p>
        </div>
    </div>
</div>

views/platos/create.php
<?php

/* @var $this yii\web\View */
/* @var $model app\models\Platos */

?>
<div class="platos-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/platos/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
 use kartik\icons\Icon;

Icon::map($this, Icon::FA);

$model = new \app\models\Platos;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
$this->title = 'Casa Macorra - Platos';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="platos-index">
    <div class="header">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-end row">
                    <div class="col">
                        <h1 class="header-titulo">Platos</h1>
                    </div>
                    <div class="col-auto">
                    <?= Html::button("Añadir plato ".Icon::show('pen', ['class' => 'fa-solid', 'framework' => Icon::FAS]),
                    ['value'=>Url::to(['platos/create']),
                    'class' => 'shadow lift btn btn-primary',
                    'id'=>'modalButton']) ?>
                    <?php
                        yii\bootstrap4\Modal::begin([
                            'title'=>'Crear plato',
                            'titleOptions'=>['class'=>"title-modal-extendido"],
                            'headerOptions'=>['class'=>"header-modal-extendido"],
                            'closeButton' =>['class'=>"btn btn-link boton-cerrar-modal"],
                            'bodyOptions' =>['class'=>"modal-body-extendido"],
                            'centerVertical'=>true,
                            'id'     =>'modal',
                            'size'   =>'modal-md',
                            'clientOptions' => ['backdrop' => 'static', 'keyboard' => FALSE]
                           ]);
                        echo "<div id='modalContent'> </div>";
                        yii\bootstrap4\Modal::end();
                    ?>
                    </div>
                </div>
            </div>
            <div class="card-body">
    <?php Pjax::begin(); ?>
            <?php
                $gridColumns = [
                    [
                        'class'=>'kartik\grid\DataColumn',
                        'contentOptions'=>['class'=>'kartik-sheet-style'],
                        'width'=>'36px',
                        'attribute' => 'ingredientes',
                        'label'=>'Ingredientes',
                        'pageSummary'=>'Total',
                        'pageSummaryOptions' => ['colspan' => 2],
                        'hAlign' => 'center', 
                        'vAlign' => 'middle',
                    ],
                    [                
                        'class'=>'kartik\grid\DataColumn',
                        'contentOptions'=>['class'=>'kartik-sheet-style'],
                        'width'=>'36px',
                        'attribute' => 'gr',
                        'label'=>'Gramos',
                        'hAlign' => 'center', 
                        'vAlign' => 'middle',
                    ],
                    [
                        'class'=>'kartik\grid\DataColumn',
                        'contentOptions'=>['class'=>'kartik-sheet-style'],
                        'width'=>'36px',
                        'attribute' => 'precio',
                        'label'=>'Precio',
                        'pageSummary'=>true,
                        'pageSummaryOptions' => ['colspan' => 6],
                        'hAlign' => 'center', 
                        'vAlign' => 'middle',
                    ],
                    [
                        'class' => 'kartik\grid\ActionColumn',
                        'dropdown' => 'dropdown',
                        'dropdownOptions' => ['class' => 'float-center'],
                        'urlCreator' => function($action, $model, $key, $index) { 
                            return Url::toRoute([$action, 'id' => $model['id']]); 
                        },
                        'viewOptions' => ['title' => 'Ver en detalle', 'data-toggle' => 'tooltip'],
                        'updateOptions' => ['title' => 'Modificar registro', 'data-toggle' => 'tooltip'],
                        'deleteOptions' => ['title' => 'Eliminar', 'data-toggle' => 'tooltip'],
                        'headerOptions' => ['class' => 'kartik-sheet-style'],
                    ],
                ];

                

                
                echo \kartik\grid\GridView::widget([
                        'dataProvider' => $ingredientes,
                        'columns' => $gridColumns,
                        'beforeHeader'=>[
                            [
                                'options'=>['class'=>'skip-export']
                            ]
                        ],
                        'toolbar' =>  [
                            'content' =>
                                Html::button("Crear proveedor ".Icon::show('pen', ['class' => 'fa-solid', 'framework' => Icon::FAS]),['value'=>Url::to(['proveedores/create']),'class' => 'buttonmodal shadow lift btn-sm btn-primary','id'=>'#modalButton0'])         
                        , 
                            'options' => ['class' => 'btn-group mr-2 me-2'],
                            '{export}',
                            '{toggleData}'
                        ],
                        'exportConfig' => [
                            'csv' => [],
                            'json' => [],
                        ],
                        'pjax' => false,
                        'bordered' => true,
                        'striped' => true,
                        'condensed' => false,
                        'responsive' => true,
                        'hover' => true,
                        'floatHeader' => true,
                        'showPageSummary' => false,
                        'pageSummaryContainer' => ['class' => 'kv-page-summary-container'],
                        'itemLabelSingle' => 'Proveedor',
                        'itemLabelPlural' => 'Proveedores',
                        'toggleDataContainer' => ['class' => 'btn-group mr-2 me-2'],
                        'persistResize' => false,
                        'toggleDataOptions' => ['minCount' => 10],
                        'panel' => [
                            'heading'=>'<h3 class="panel-title">'.Icon::show('address-book', ['class' => 'fa-solid', 'framework'=> Icon::FAS]).'&nbsp;&nbsp;Proveedores</h3>',
                            'headingOptions'=>['class'=>'panel-heading table-color rounded-top'],
                            'footer' => false,
                        ],
                ]);
                
            ?>
            <?php Pjax::end(); ?>
    </div>
</div>

        </div>
    </div>
</div>

views/platos/update.php
<?php

?>
<div class="platos-update">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/platos/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Platos */

$this->title = $model->nombre;
$this->params['breadcrumbs'][] = ['label' => 'Platos', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="platos-view">

    <h1 class="text-center pt-3"><?= Html::encode($this->title) ?></h1>


    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'nombre',
            'categoría',
            'precio_publico',
            'coste',
        ],
    ]) ?>

    <p class="text-right">
        <?= Html::a('Actualizar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'head'=>'Confirmación',
                'confirm' => '¿Estás seguro que quieres eliminar '.$this->title.'?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
</div>

views/platos/vistaPlatos.php
<?php

use yii\widgets\ListView;
use yii\helpers\Html;
use yii\helpers\Url;
use kartik\icons\Icon;

Icon::map($this, Icon::FA);
$this->title = 'Casa Macorra - Platos';
$this->params['breadcrumbs'][] = $this->title;
$model = new \app\models\Platos;
?>

<div class="platos-index">
    <div class="header">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-end row">
                    <div class="col">
                        <h1 class="header-titulo">Platos</h1>
                    </div>
                    <div class="col-auto">
                    <?= Html::button("Añadir plato ".Icon::show('pen', ['class' => 'fa-solid', 'framework' => Icon::FAS]),
                    ['value'=>Url::to(['/platos/create']),
                    'class' => 'buttonmodal shadow lift btn btn-primary',
                    'id'=>'modalButton',
                    'data-id'=>$model->id,
                    'data-tittle'=>'Crear plato']) ?>
                    <?php
                        yii\bootstrap4\Modal::begin([
                            'title'=>'Crear plato',
                            'titleOptions'=>['class'=>"title-modal-extendido"],
                            'headerOptions'=>['class'=>"header-modal-extendido"],
                            'closeButton' =>['class'=>"btn btn-link boton-cerrar-modal"],
                            'bodyOptions' =>['class'=>"modal-body-extendido"],
                            'centerVertical'=>true,
                            'id'     =>'modal0',
                            'size'   =>'modal-md',
                            'clientOptions' => ['backdrop' => 'static', 'keyboard' => FALSE]
                           ]);
                        echo "<div id='modalContent0'> </div>";
                        yii\bootstrap4\Modal::end();
                    ?>
                    </div>
                </div>
            </div>
        <?= ListView::widget([
        'dataProvider'=>$dataProvider,
        'itemView'=>'_vistaPlatos',
        'summary'=>false,
        'options' => [
            'tag' => 'div',
            'class' => 'row',
        ],
        'layout'=>"{summary}\n{pager}\n{items}",
        'itemOptions'=>['tag' => 'div',
            'class' => 'p-4 col-lg-12 col-sm-12',]
        ]);?>
        </div>
    </div>
</div>