models/Comandas.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "comandas".
 *
 * @property int $id
 * @property string|null $fecha
 * @property float|null $precio_total
 * @property int|null $id_plato
 * @property int|null $cantidad
 *
 * @property Platos $plato
 */
class Comandas extends \yii\db\ActiveRecord
{
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'comandas';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_plato'], 'integer'],
            [['id_plato'], 'exist', 'skipOnError' => true, 'targetClass' => Platos::class, 'targetAttribute' => ['id_plato' => 'id']],
            [['cantidad'],'required'],
            [['cantidad'], 'integer','min' => 1, 'max' => 50000]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fecha' => 'Fecha',
            'precio_total' => 'Precio Total',
            'id_plato' => 'Plato',
            'cantidad' => 'Cantidad',
        ];
    }

    /**
     * Gets query for [[Plato]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPlato()
    {
        return $this->hasOne(Platos::class, ['id' => 'id_plato']);
    }
    
    public function getdropdownPlato(){
        $models = Platos::find()->asArray()->all();
        
        return \yii\helpers\ArrayHelper::map($models, 'id', 'nombre');
    }
    
    
    
}

controllers/ComandasController.php
<?php

namespace app\controllers;
use Yii;
use app\models\Comandas;
use yii\grid\ActionColumn;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Expression;
use yii\helpers\Url;

use app\models\Platos;

/**
 * ComandasController implements the CRUD actions for Comandas model.
 */
class ComandasController extends Controller
{
    
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Comandas models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $expresion = new Expression('comandas.id,comandas.fecha, platos.nombre, concat(comandas.cantidad, " Und.")');
        $searchModel = new \app\models\ComandasSearch();
        $query = (new \yii\db\Query())->select($expresion)
                ->from('comandas')
                ->join('LEFT JOIN', 'platos', 'comandas.id_plato = platos.id')
                ->orderBy('fecha desc');
        $gridColumns = [
            [
                'class'=>'kartik\grid\DataColumn',
                'contentOptions'=>['class'=>'kartik-sheet-style'],
                'width'=>'36px',
                'attribute' => 'fecha',
                'format'=>['date', 'php:d-m-Y'],
                'label'=>'Fecha',
                'pageSummary'=>'Total',
                'pageSummaryOptions' => ['colspan' => 2],
                'hAlign' => 'center', 
                'vAlign' => 'middle',
            ],
            [                
                'class'=>'kartik\grid\DataColumn',
                'contentOptions'=>['class'=>'kartik-sheet-style'],
                'width'=>'36px',
                'attribute' => 'nombre',
                'label'=>'Nombre',
                'hAlign' => 'center', 
                'vAlign' => 'middle',
            ],
            [
                'class'=>'kartik\grid\FormulaColumn',
                'contentOptions'=>['class'=>'kartik-sheet-style'],
                'width'=>'36px',
                'attribute' => 'concat(comandas.cantidad, " Und.")',
                'label'=>'Cantidad',
                'hAlign' => 'center', 
                'vAlign' => 'middle',
                'pageSummary'=>true,
            ],
            [
                'class' => 'kartik\grid\ActionColumn',
                'dropdown' => 'dropdown',
                'dropdownOptions' => ['class' => 'float-center'],
                'urlCreator' => function($action, $model, $key, $index) { 
                    return Url::toRoute([$action, 'id' => $model['id']]); 
                },
                'viewOptions' => ['title' => 'Ver en detalle', 'data-toggle' => 'tooltip'],
                'updateOptions' => ['title' => 'Modificar registro', 'data-toggle' => 'tooltip'],
                'deleteOptions' => ['title' => 'Eliminar', 'data-toggle' => 'tooltip'],
                'headerOptions' => ['class' => 'kartik-sheet-style'],
            ],
        ];
        
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
           
            'pagination' => [
                'pageSize' => 10
            ],
            /*
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel'=>$searchModel,
            'gridColumns'=>$gridColumns,
        ]);
    }

    /**
     * Displays a single Comandas model.
     * @param int $id ID
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Comandas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new Comandas();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['index']);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->renderAjax('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Comandas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Comandas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        
        return $this->redirect(['index']);
    }

    /**
     * Finds the Comandas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Comandas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Comandas::findOne(['id' => $id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
    
    public function actionMes()
    {
        $gridColumns = [
            [
                'class'=>'kartik\grid\DataColumn',
                'contentOptions'=>['class'=>'kartik-sheet-style'],
                'width'=>'36px',
                'attribute' => 'año',
                'label'=>'Año',
                'pageSummary'=>'Total',
                'pageSummaryOptions' => ['colspan' => 2],
                'hAlign' => 'center', 
                'vAlign' => 'middle',
            ],
            [                
                'class'=>'kartik\grid\DataColumn',
                'contentOptions'=>['class'=>'kartik-sheet-style'],
                'width'=>'36px',
                'attribute' => 'Mes',
                'label'=>'Mes',
                'hAlign' => 'center', 
                'vAlign' => 'middle',
            ],
            [
                'class'=>'kartik\grid\DataColumn',
                'contentOptions'=>['class'=>'kartik-sheet-style'],
                'width'=>'36px',
                'attribute' => 'Cantidad de platos',
                'label'=>'Cantidad de platos',
                'pageSummary'=>true,
                'pageSummaryOptions' => ['colspan' => 6],
                'hAlign' => 'center', 
                'vAlign' => 'middle',
            ],
        ];
        $expresion = new Expression("year(fecha) as año, elt(MONTH(fecha),'Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre') as Mes, concat(sum(cantidad),' platos') as 'Cantidad de platos'");
        $query = (new \yii\db\Query())->select($expresion)
                ->from('comandas')
                ->groupBy('month(fecha), year(fecha)')
                ->orderBy('año desc, fecha asc');
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            
            'pagination' => [
                'pageSize' => 10
            ],
             /*
            'sort' => [
                'defaultOrder' => [
                    'año' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'gridColumns'=>$gridColumns
        ]);
    }
    
    public function actionYear()
    {
        $gridColumns = [
            [
                'class'=>'kartik\grid\DataColumn',
                'contentOptions'=>['class'=>'kartik-sheet-style'],
                'width'=>'36px',
                'attribute' => 'año',
                'label'=>'Año',
                'pageSummary'=>'Total',
                'pageSummaryOptions' => ['colspan' => 1],
                'hAlign' => 'center', 
                'vAlign' => 'middle',
            ],
            [
                'class'=>'kartik\grid\DataColumn',
                'contentOptions'=>['class'=>'kartik-sheet-style'],
                'width'=>'36px',
                'attribute' => 'Cantidad de platos',
                'label'=>'Cantidad de platos',
                'pageSummary'=>true,
                'hAlign' => 'center', 
                'vAlign' => 'middle',
            ],
        ];
        $expresion = new Expression("year(fecha) as año, concat(sum(cantidad),' platos') as 'Cantidad de platos'");
        $query = (new \yii\db\Query())->select($expresion)
                ->from('comandas')
                ->groupBy('year(fecha)')
                ->orderBy('año desc');
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            
            'pagination' => [
                'pageSize' => 10
            ],
             /*
            'sort' => [
                'defaultOrder' => [
                    'año' => SORT_DESC,

views/comandas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Comandas */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="comandas-form">

    <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'id_plato')->dropDownList($model->getdropdownPlato())->label('plato vendido',['class'=>'texto-formularios']) ?>

        <?= $form->field($model, 'cantidad')->textInput()->label('Cantidad vendida',['class'=>'texto-formularios']) ?>

        <div class="form-group">
            <?= Html::submitButton('Guardar', ['class' => 'shadow lift btn btn-primary']) ?>
            <?= Html::a("Volver", ['comandas/index'], ['class' => 'shadow lift btn btn-secondary']) ?>
        </div>
    <?php ActiveForm::end(); ?>
</div>

views/comandas/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ComandasSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="comandas-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'fecha') ?>

    <?= $form->field($model, 'precio_total') ?>

    <?= $form->field($model, 'id_plato') ?>

    <?= $form->field($model, 'cantidad') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/comandas/create.php
<?php


/* @var $this yii\web\View */
/* @var $model app\models\Comandas */

?>


<div class="comandas-create">
<?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/comandas/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\ActionColumn;
use yii\widgets\Pjax;

use kartik\icons\Icon;
use kartik\grid\GridView;
use kartik\bs4dropdown\Dropdown;
use kartik\bs4dropdown\ButtonDropdown;

Icon::map($this, Icon::FA);

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
yii\bootstrap4\Modal::begin([
    'title'=>'Crear comanda',
    'titleOptions'=>['class'=>"title-modal-extendido"],
    'headerOptions'=>['class'=>"header-modal-extendido"],
    'closeButton' =>['class'=>"btn btn-link boton-cerrar-modal"],
    'bodyOptions' =>['class'=>"modal-body-extendido"],
    'centerVertical'=>true,
    'id'     =>"modal0",
    'size'   =>'modal-md',
    'clientOptions' => ['backdrop' => 'static', 'keyboard' => FALSE]
    ]);
    echo "<div id='modalContent0'> </div>";
    yii\bootstrap4\Modal::end();
?>
<div class="row row-space pt-3">
    <div class="col m-3">
        <?=
            Html::button("Añadir comanda ".Icon::show('pen', ['class' => 'fa-solid', 'framework' => Icon::FAS]),
            ['value'=>Url::to(['comandas/create']),
            'class' => 'buttonmodal shadow lift btn btn-primary float-right',
            'id'=>'#modalButton0']) 
        ?>
    </div>
    <div class="col-12">
        <div class="card shadow-sm m-3">
            <?php Pjax::begin(); ?>
            <?php
                echo \kartik\grid\GridView::widget([
                        'dataProvider' => $dataProvider,
                        'columns' => $gridColumns,
                        'beforeHeader'=>[
                            [
                                'options'=>['class'=>'skip-export']
                            ]
                        ],
                        'toolbar' =>  [
                            'content' =>
                                Html::a('Mes', ['mes'], ['class' => 'btn btn-outline-secondary','title'=>('Mes')]). ' '.
                                Html::a('Año', ['year'], ['class' => 'btn btn-outline-secondary','title'=>('Año')]). ' '.
                                Html::a('<i class="fas fa-redo"></i>', ['index'], ['class' => 'btn btn-outline-secondary','title'=>('Reset Grid'),'data-pjax' => 0,
                        ]), 
                            'options' => ['class' => 'btn-group mr-2 me-2'],
                            '{export}',
                            '{toggleData}'
                        ],
                        'exportConfig' => [
                            'txt' => [],
                            'xls' => [],
                        ],
                        'export' => [
                            'header'=>'<li role="presentation" class="dropdown-header">Exportar datos de esta tabla</li>',
                        ],
                        'pjax' => false,
                        'bordered' => true,
                        'striped' => true,
                        'condensed' => false,
                        'responsive' => true,
                        'hover' => true,
                        'floatHeader' => true,
                        'showPageSummary' => true,
                        'pageSummaryContainer' => ['class' => 'kv-page-summary-container'],
                        'itemLabelSingle' => 'Comanda',
                        'itemLabelPlural' => 'Comandas',
                        'toggleDataContainer' => ['class' => 'btn-group mr-2 me-2'],
                        'persistResize' => false,
                        'toggleDataOptions' => ['minCount' => 10],
                        'panel' => [
                            'heading'=>'<h3 class="panel-title">'.Icon::show('edit', ['class' => 'fa-solid', 'framework'=> Icon::FAS]).'&nbsp;&nbsp;Comandas</h3>',
                            'headingOptions'=>['class'=>'panel-heading table-color rounded-top'],
                        ],
                ]);
            ?>
            <?php Pjax::end(); ?>
        </div>
    </div>
</div>

views/comandas/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Comandas */

$this->title = $model->fecha;
$this->params['breadcrumbs'][] = ['label' => 'Comandas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="comandas-update">
<div class="card shadow-sm m-3">
        <div class="card-header">
            <div class="row">
                <div class="col-6">
                    <h1>Actualizar comanda del día:</h1>
                </div>
                <div class="col-6">
                    <h1 class="text-right"><?= Html::encode($this->title) ?></h1>
                </div>
            </div>
        </div>
        <div class="card-body">
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>
</div>

views/comandas/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Comandas */

$this->title = $model->fecha;
$this->params['breadcrumbs'][] = ['label' => 'Comandas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="comandas-view">
<div class="card shadow-sm m-3">
        <div class="card-header">
            <div class="row">
                <div class="col-6">
                    <h1 >Comanda del dia: <?= Html::encode(Yii::$app->formatter->asDate($this->title, 'dd-MM-yyyy')) ?></h1>
                </div>
            </div>
        </div>
        <div class="card-body">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'fecha',
                    'precio_total',
                    'id_plato',
                    'cantidad',
                ],
            ]) ?>
            <p>
                <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                <?= Html::a('Delete', ['delete', 'id' => $model->id], [
                    'class' => 'btn btn-danger',
                    'data' => [
                        'confirm' => '¿Estás seguro de eliminar el registro?',
                        'method' => 'post',
                    ],
                ]) ?>
                <?= Html::a("Volver", ['comandas/index'], ['class' => 'shadow lift btn btn-secondary']) ?>
            </p>
        </div>
    </div>


</div>